name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      run: docker login -u ${{ DockerHub.DOCKERHUB_USERNAME }} -p ${{ DockerHub.DOCKERHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
          docker build -t ${{ DockerHub.DOCKERHUB_USERNAME }}/ddns-online-scaleway:latest .
          docker push ${{ DockerHub.DOCKERHUB_USERNAME }}/ddns-online-scaleway:latest
